-- Product image metadata only. Run in Supabase SQL Editor or apply as a migration.
BEGIN;

CREATE TABLE public.product_assets (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id bigint NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  asset_type text NOT NULL DEFAULT 'image',
  storage_path text NOT NULL,
  file_name text,
  alt_text text,
  sort_order integer NOT NULL DEFAULT 0,
  is_primary boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT product_assets_asset_type_check CHECK (asset_type = 'image')
);

CREATE INDEX product_assets_product_sort_order_idx
  ON public.product_assets (product_id, sort_order);

ALTER TABLE public.product_assets ENABLE ROW LEVEL SECURITY;

-- Match the explicitly requested anon CRUD access for this development environment.
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.product_assets TO anon;
GRANT USAGE, SELECT ON SEQUENCE public.product_assets_id_seq TO anon;

CREATE POLICY product_assets_anon_select
  ON public.product_assets FOR SELECT TO anon USING (true);

CREATE POLICY product_assets_anon_insert
  ON public.product_assets FOR INSERT TO anon WITH CHECK (true);

CREATE POLICY product_assets_anon_update
  ON public.product_assets FOR UPDATE TO anon USING (true) WITH CHECK (true);

CREATE POLICY product_assets_anon_delete
  ON public.product_assets FOR DELETE TO anon USING (true);

COMMIT;
