-- Apply once after blog_tasks exists. Additive: product_assets and existing rows are untouched.
BEGIN;

CREATE TABLE public.blog_task_assets (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  blog_task_id bigint NOT NULL REFERENCES public.blog_tasks(id) ON DELETE CASCADE,
  storage_path text NOT NULL UNIQUE,
  file_name text NOT NULL,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX blog_task_assets_task_order_idx
  ON public.blog_task_assets (blog_task_id, sort_order, id);

ALTER TABLE public.blog_task_assets ENABLE ROW LEVEL SECURITY;

-- Same internal-development publishable/anon client access as product_assets.
GRANT SELECT, INSERT, DELETE ON public.blog_task_assets TO anon, authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.blog_task_assets_id_seq TO anon, authenticated;

CREATE POLICY blog_task_assets_read ON public.blog_task_assets
  FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY blog_task_assets_insert ON public.blog_task_assets
  FOR INSERT TO anon, authenticated WITH CHECK (true);
CREATE POLICY blog_task_assets_delete ON public.blog_task_assets
  FOR DELETE TO anon, authenticated USING (true);

INSERT INTO storage.buckets (id, name, public, allowed_mime_types)
VALUES ('blog-task-assets', 'blog-task-assets', false,
        ARRAY['image/jpeg', 'image/png', 'image/webp']::text[])
ON CONFLICT (id) DO UPDATE
SET public = false, allowed_mime_types = EXCLUDED.allowed_mime_types;

CREATE POLICY blog_task_assets_storage_insert ON storage.objects
  FOR INSERT TO anon, authenticated
  WITH CHECK (
    bucket_id = 'blog-task-assets'
    AND (storage.foldername(name))[1] = 'tasks'
    AND EXISTS (SELECT 1 FROM public.blog_tasks AS task
      WHERE task.id::text = (storage.foldername(name))[2])
  );

CREATE POLICY blog_task_assets_storage_read ON storage.objects
  FOR SELECT TO anon, authenticated
  USING (
    bucket_id = 'blog-task-assets'
    AND (storage.foldername(name))[1] = 'tasks'
    AND EXISTS (SELECT 1 FROM public.blog_tasks AS task
      WHERE task.id::text = (storage.foldername(name))[2])
  );

CREATE POLICY blog_task_assets_storage_delete ON storage.objects
  FOR DELETE TO anon, authenticated
  USING (
    bucket_id = 'blog-task-assets'
    AND (storage.foldername(name))[1] = 'tasks'
    AND EXISTS (SELECT 1 FROM public.blog_tasks AS task
      WHERE task.id::text = (storage.foldername(name))[2])
  );

COMMIT;
